In [1]:
import pandas as pd

In [ ]:
general_info_file_path = "extracting_company_data/general_info.csv"
df_general_info = pd.read_csv(general_info_file_path)
display(df_general_info)
review_classes_file_path = "extracting_company_data/review_classes.csv"
df_review_classes = pd.read_csv(review_classes_file_path)
display(df_review_classes)

,company,website,rating,number_review,domain
0,Viator.com,www.viator.com,4.4,260639.0,['Travel Agency']
1,JustFly,justfly.com,4.2,194179.0,"['Travel Agency', 'Flights Search Site']"
2,Vegas.com,www.vegas.com,4.6,163448.0,['Travel Agency']
3,Gotogate,www.gotogate.com,3.1,141912.0,['Travel & Vacation']
4,Allianz Partners USA,www.allianztravelinsurance.com,4.1,126673.0,"['Travel Insurance Company', 'Financial Consul..."
...,...,...,...,...,...
1035,Buckingham Luxury Vacation Rentals,buckinghamtahoerentals.com,4.3,102.0,"['Vacation Rental', 'Travel Agency']"
1036,Descapada,descapada.com,4.2,102.0,"['Travel Aggregator', 'Tour Operator', 'Tour A..."
1037,Oru Kayak,www.orukayak.com,2.8,102.0,['Travel & Vacation']
1038,TRIPOMATE,www.tripomate.com,1.7,102.0,"['Travel Aggregator', 'Travel Agency']"
1039,Flo Tours,www.flotours.com,4.9,101.0,"['Travel Agency', 'Tour Operator']"

,website,5_star_percentage,4_star_percentage,3_star_percentage,2_star_percentage,1_star_percentage
0,www.flydealfare.com,95%,4%,<1%,<1%,<1%
1,peruforless.com,96%,3%,<1%,0%,0%
2,www.rockymountaingetaways.com,99%,<1%,<1%,0%,<1%
3,monarchairgroup.com,98%,2%,<1%,0%,<1%
4,incaexpert.com,98%,2%,0%,0%,0%
...,...,...,...,...,...,...
1039,www.bookingbuddy.com,37%,13%,12%,6%,32%
1040,tripping.com,89%,4%,1%,1%,5%
1041,hotelvalue.com,<1%,<1%,<1%,<1%,99%
1042,smokymtndreams.com,62%,16%,8%,3%,11%
1043,lowcostairlines.com,56%,23%,10%,2%,9%

In [12]:
df_companies = (
    df_general_info
    .merge(df_review_classes, how="left", on="website")
    )
display(df_companies)
display(df_companies.isna().sum())

,company,website,rating,number_review,domain,5_star_percentage,4_star_percentage,3_star_percentage,2_star_percentage,1_star_percentage
0,Viator.com,www.viator.com,4.4,260639.0,['Travel Agency'],72%,9%,4%,3%,12%
1,JustFly,justfly.com,4.2,194179.0,"['Travel Agency', 'Flights Search Site']",71%,16%,3%,2%,8%
2,Vegas.com,www.vegas.com,4.6,163448.0,['Travel Agency'],75%,14%,5%,2%,4%
3,Gotogate,www.gotogate.com,3.1,141912.0,['Travel & Vacation'],35%,17%,9%,7%,32%
4,Allianz Partners USA,www.allianztravelinsurance.com,4.1,126673.0,"['Travel Insurance Company', 'Financial Consul...",73%,6%,3%,2%,16%
...,...,...,...,...,...,...,...,...,...,...
1035,Buckingham Luxury Vacation Rentals,buckinghamtahoerentals.com,4.3,102.0,"['Vacation Rental', 'Travel Agency']",78%,10%,4%,5%,3%
1036,Descapada,descapada.com,4.2,102.0,"['Travel Aggregator', 'Tour Operator', 'Tour A...",75%,2%,<1%,4%,18%
1037,Oru Kayak,www.orukayak.com,2.8,102.0,['Travel & Vacation'],44%,8%,7%,15%,26%
1038,TRIPOMATE,www.tripomate.com,1.7,102.0,"['Travel Aggregator', 'Travel Agency']",3%,3%,10%,4%,80%
1039,Flo Tours,www.flotours.com,4.9,101.0,"['Travel Agency', 'Tour Operator']",71%,14%,7%,3%,5%

company              0
website              0
rating               1
number_review        1
domain               0
5_star_percentage    1
4_star_percentage    1
3_star_percentage    1
2_star_percentage    1
1_star_percentage    1
dtype: int64

In [13]:

reviews_path = "reviews_extracting/trustpilot_reviews_2.csv"
df_reviews = pd.read_csv(reviews_path)
display(df_reviews)

,name,country,rating,title,text,date_of_experience,has_reply,company
0,Przemysław Rosuł,PL,1,Ignoring the specified pickup time,Ignoring the specified pickup time. Providing ...,2025-05-13,0,www.viator.com
1,kathy mrozek,US,5,Athens Evening food tour with Katrina,"Katrina, the tour guide was fabulous! She mad...",2025-05-15,0,www.viator.com
2,MARY MURRAY,US,5,All you need for travel with confidence,A great app! My excursions have been awesome! ...,2025-05-12,0,www.viator.com
3,K Shay Smith,MX,1,I booked the excursion and paid the…,I booked the excursion and paid the money up f...,2025-05-12,0,www.viator.com
4,Jeff Paine,US,5,Great food tour of Prague. Great conversation ...,Great food tour of Prague,2025-05-07,0,www.viator.com
...,...,...,...,...,...,...,...,...
21093,Asma,US,1,I rented a car with Expedia and paid…,I rented a car with Expedia and paid the money...,2025-02-08,0,www.expedia.com
21094,Algirdas Dembinskas,US,1,Platinum user review,I’ve been using Expedia frequently for over 10...,2025-02-16,0,www.expedia.com
21095,Erin McLaughlin,US,1,NEVER book a flight through Expedia,NEVER book a flight through Expedia. “Fully re...,2025-02-15,0,www.expedia.com
21096,Lane Rosen,US,1,Expedia a Very deceptive company,Very deceptive company. Charge double the reg...,2025-02-14,0,www.expedia.com
21097,Darren,GB,1,Expedia are now offering non refundable insect...,Expedia do not take any responsibility for wha...,2025-01-17,0,www.expedia.com

In [ ]:
reviews_path = "reviews_extracting/trustpilot_reviews.csv"
df_reviews = pd.read_csv(reviews_path)
display(df_reviews)
reviews_path = "reviews_extracting/trustpilot_reviews_2.csv"
df_reviews = pd.read_csv(reviews_path)
display(df_reviews)
reviews_path = "reviews_extracting/trustpilot_reviews_15pages.csv"
df_reviews = pd.read_csv(reviews_path)
display(df_reviews)

In [15]:
display(df_reviews.shape)
display(df_companies.shape)
df_merged = (df_reviews
    .merge(df_companies, 
           how="left", 
           left_on="company",
           right_on="website",
           ))
display(
    df_merged
            )
display(
    df_merged
    .isna()
    .sum()
    )

(21098, 8)

(1040, 10)

,name,country,rating_x,title,text,date_of_experience,has_reply,company_x,company_y,website,rating_y,number_review,domain,5_star_percentage,4_star_percentage,3_star_percentage,2_star_percentage,1_star_percentage
0,Przemysław Rosuł,PL,1,Ignoring the specified pickup time,Ignoring the specified pickup time. Providing ...,2025-05-13,0,www.viator.com,Viator.com,www.viator.com,4.4,260639.0,['Travel Agency'],72%,9%,4%,3%,12%
1,kathy mrozek,US,5,Athens Evening food tour with Katrina,"Katrina, the tour guide was fabulous! She mad...",2025-05-15,0,www.viator.com,Viator.com,www.viator.com,4.4,260639.0,['Travel Agency'],72%,9%,4%,3%,12%
2,MARY MURRAY,US,5,All you need for travel with confidence,A great app! My excursions have been awesome! ...,2025-05-12,0,www.viator.com,Viator.com,www.viator.com,4.4,260639.0,['Travel Agency'],72%,9%,4%,3%,12%
3,K Shay Smith,MX,1,I booked the excursion and paid the…,I booked the excursion and paid the money up f...,2025-05-12,0,www.viator.com,Viator.com,www.viator.com,4.4,260639.0,['Travel Agency'],72%,9%,4%,3%,12%
4,Jeff Paine,US,5,Great food tour of Prague. Great conversation ...,Great food tour of Prague,2025-05-07,0,www.viator.com,Viator.com,www.viator.com,4.4,260639.0,['Travel Agency'],72%,9%,4%,3%,12%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21093,Asma,US,1,I rented a car with Expedia and paid…,I rented a car with Expedia and paid the money...,2025-02-08,0,www.expedia.com,Expedia,www.expedia.com,1.2,10149.0,"['Travel Aggregator', 'Travel Agency']",4%,<1%,<1%,2%,92%
21094,Algirdas Dembinskas,US,1,Platinum user review,I’ve been using Expedia frequently for over 10...,2025-02-16,0,www.expedia.com,Expedia,www.expedia.com,1.2,10149.0,"['Travel Aggregator', 'Travel Agency']",4%,<1%,<1%,2%,92%
21095,Erin McLaughlin,US,1,NEVER book a flight through Expedia,NEVER book a flight through Expedia. “Fully re...,2025-02-15,0,www.expedia.com,Expedia,www.expedia.com,1.2,10149.0,"['Travel Aggregator', 'Travel Agency']",4%,<1%,<1%,2%,92%
21096,Lane Rosen,US,1,Expedia a Very deceptive company,Very deceptive company. Charge double the reg...,2025-02-14,0,www.expedia.com,Expedia,www.expedia.com,1.2,10149.0,"['Travel Aggregator', 'Travel Agency']",4%,<1%,<1%,2%,92%
21097,Darren,GB,1,Expedia are now offering non refundable insect...,Expedia do not take any responsibility for wha...,2025-01-17,0,www.expedia.com,Expedia,www.expedia.com,1.2,10149.0,"['Travel Aggregator', 'Travel Agency']",4%,<1%,<1%,2%,92%

name                  3
country               2
rating_x              0
title                 2
text                  0
date_of_experience    0
has_reply             0
company_x             0
company_y             0
website               0
rating_y              0
number_review         0
domain                0
5_star_percentage     0
4_star_percentage     0
3_star_percentage     0
2_star_percentage     0
1_star_percentage     0
dtype: int64

In [ ]:
# df_merged.to_csv("all_data.csv", index=False)