In [ ]:
import pandas as pd
import ast

# --- 1. Load Data ---
df_final = pd.read_csv('../../1_data_collection/extracting_company_data/general_info.csv')
print(f"Data loaded. Total rows: {len(df_final)}")

# --- 2. Prepare 'Domain' Column ---
if not df_final.empty and isinstance(df_final['domain'].iloc[0], str):
    df_final['domain'] = df_final['domain'].apply(lambda x: ast.literal_eval(x))
else:
    print("Domain column appears to contain lists or is empty. No string evaluation needed.")

# --- 3. Explode and Clean Domains ---
df_domain_table = df_final.explode('domain')
df_domain_table['domain'] = df_domain_table['domain'].str.replace(r'\.\.\.$', '', regex=True).str.strip()

# --- 4. Count Domain Frequency ---
domain_counts = df_domain_table['domain'].value_counts().reset_index()
domain_counts.columns = ['domain', 'count']

# --- 5. Generate domain_id in format "rank_count" ---
domain_counts['domain_id'] = domain_counts.reset_index().index + 1  # Rank
domain_counts['domain_id'] = domain_counts['domain_id'].astype(str) + '_' + domain_counts['count'].astype(str)

# --- 6. Final Domain Table ---
domain_df = domain_counts[['domain_id', 'domain']]

# --- 7. Create Company_Domain Table ---
company_domain_df = df_domain_table.merge(domain_df, on='domain', how='left')
company_domain_df = company_domain_df[['website', 'domain_id']]

# --- 8. Output ---
print("\n--- Domain Table ---")
print(domain_df.head())

print("\n--- Company_Domain Table ---")
print(company_domain_df.head())

Data loaded. Total rows: 1040

--- Domain Table ---
  domain_id               domain
0     1_721        Travel Agency
1     2_205  Flights Search Site
2     3_165        Tour Operator
3     4_132    Travel Aggregator
4      5_94      Vacation Rental

--- Company_Domain Table ---
            website domain_id
0    www.viator.com     1_721
1       justfly.com     1_721
2       justfly.com     2_205
3     www.vegas.com     1_721
4  www.gotogate.com      8_76

In [11]:

domain_df.to_csv('domain_table.csv', index=False)
company_domain_df.to_csv('company_domain_table.csv', index=False)

In [9]:
company_domain_df.head(20)

                           website domain_id
0                   www.viator.com     1_721
1                      justfly.com     1_721
2                      justfly.com     2_205
3                    www.vegas.com     1_721
4                 www.gotogate.com      8_76
5   www.allianztravelinsurance.com     19_17
6   www.allianztravelinsurance.com     29_10
7   www.allianztravelinsurance.com     1_721
8   www.allianztravelinsurance.com      34_8
9                     www.vrbo.com      5_94
10                    www.vrbo.com     1_721
11                   flighthub.com     2_205
12                   flighthub.com     1_721
13             www.asaptickets.com     1_721
14             www.asaptickets.com     2_205
15             www.asaptickets.com      6_91
16               www.priceline.com     1_721
17               www.priceline.com     2_205
18                     www.way.com     1_721
19                     www.way.com     16_19

In [10]:
#Analyze company column
domain_df.head(20)

   domain_id                         domain
0      1_721                  Travel Agency
1      2_205            Flights Search Site
2      3_165                  Tour Operator
3      4_132              Travel Aggregator
4       5_94                Vacation Rental
5       6_91          Airline Ticket Agency
6       7_84                          Hotel
7       8_76              Travel & Vacation
8       9_58                        Airline
9      10_42                    Tour Agency
10     11_32                  Cruise Agency
11     12_31        Cultural Tours Provider
12     13_23                Visa Consultant
13     14_22           Cruise Travel Agency
14     15_22    Vacation Home Rental Agency
15     16_19                    Parking Lot
16     17_19       Visa and Passport Office
17     18_18  Holiday Accommodation Service
18     19_17       Travel Insurance Company
19     20_14         Transportation Service